# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetMeterData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetMeterData.proto',
  package='testgRPC',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12GetMeterData.proto\x12\x08testgRPC\"7\n\x0b\x44\x61taRequest\x12\x14\n\x0c\x66romDateTime\x18\x01 \x01(\x03\x12\x12\n\ntoDateTime\x18\x02 \x01(\x03\":\n\x11MeterDataResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.testgRPC.OneMeterData\"j\n\x0cOneMeterData\x12\x0f\n\x07\x61\x63tEnIN\x18\x01 \x01(\x01\x12\x11\n\treactEnIN\x18\x02 \x01(\x01\x12\x10\n\x08\x61\x63tEnOUT\x18\x03 \x01(\x01\x12\x12\n\nreactEnOUT\x18\x04 \x01(\x01\x12\x10\n\x08\x64\x61tetime\x18\x05 \x01(\x03\x32O\n\x0cGetMeterData\x12?\n\x07GetData\x12\x15.testgRPC.DataRequest\x1a\x1b.testgRPC.MeterDataResponse\"\x00\x62\x06proto3')
)




_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='testgRPC.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromDateTime', full_name='testgRPC.DataRequest.fromDateTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toDateTime', full_name='testgRPC.DataRequest.toDateTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=87,
)


_METERDATARESPONSE = _descriptor.Descriptor(
  name='MeterDataResponse',
  full_name='testgRPC.MeterDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='testgRPC.MeterDataResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=147,
)


_ONEMETERDATA = _descriptor.Descriptor(
  name='OneMeterData',
  full_name='testgRPC.OneMeterData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actEnIN', full_name='testgRPC.OneMeterData.actEnIN', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reactEnIN', full_name='testgRPC.OneMeterData.reactEnIN', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actEnOUT', full_name='testgRPC.OneMeterData.actEnOUT', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reactEnOUT', full_name='testgRPC.OneMeterData.reactEnOUT', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='testgRPC.OneMeterData.datetime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=255,
)

_METERDATARESPONSE.fields_by_name['items'].message_type = _ONEMETERDATA
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['MeterDataResponse'] = _METERDATARESPONSE
DESCRIPTOR.message_types_by_name['OneMeterData'] = _ONEMETERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'GetMeterData_pb2'
  # @@protoc_insertion_point(class_scope:testgRPC.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

MeterDataResponse = _reflection.GeneratedProtocolMessageType('MeterDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _METERDATARESPONSE,
  '__module__' : 'GetMeterData_pb2'
  # @@protoc_insertion_point(class_scope:testgRPC.MeterDataResponse)
  })
_sym_db.RegisterMessage(MeterDataResponse)

OneMeterData = _reflection.GeneratedProtocolMessageType('OneMeterData', (_message.Message,), {
  'DESCRIPTOR' : _ONEMETERDATA,
  '__module__' : 'GetMeterData_pb2'
  # @@protoc_insertion_point(class_scope:testgRPC.OneMeterData)
  })
_sym_db.RegisterMessage(OneMeterData)



_GETMETERDATA = _descriptor.ServiceDescriptor(
  name='GetMeterData',
  full_name='testgRPC.GetMeterData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=257,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='testgRPC.GetMeterData.GetData',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_METERDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETMETERDATA)

DESCRIPTOR.services_by_name['GetMeterData'] = _GETMETERDATA

# @@protoc_insertion_point(module_scope)
